// lib/datos.dart

class CartaJuego { // <--- CORREGIDO: Antes decía CartaDatos
  final String palabra;
  final String pista;
  final String categoria; // Agregamos este campo opcional por si acaso

  CartaJuego(this.palabra, this.pista, {this.categoria = ""});

  // Para guardar/cargar preferencias personalizadas
  Map<String, dynamic> toJson() => {'palabra': palabra, 'pista': pista, 'categoria': categoria};

  factory CartaJuego.fromJson(Map<String, dynamic> json) {
    return CartaJuego(
        json['palabra'],
        json['pista'],
        categoria: json['categoria'] ?? ""
    );
  }
}

final Map<String, List<CartaJuego>> baseDeDatos = {
  // ======================================================
  // 1. LEAGUE OF LEGENDS
  // ======================================================
  "⚔️ LoL Campeones": [
    CartaJuego("Aatrox", "Fin del mundo"),
    CartaJuego("Ahri", "Esferas"),
    CartaJuego("Akali", "Humo"),
    CartaJuego("Akshan", "Resurrección"),
    CartaJuego("Alistar", "Campana"),
    CartaJuego("Amumu", "Amigos"),
    CartaJuego("Anivia", "Huevo"),
    CartaJuego("Annie", "Tibbers"),
    CartaJuego("Aphelios", "5 armas"),
    CartaJuego("Ashe", "Flecha"),
    CartaJuego("Aurelion Sol", "Estrellas"),
    CartaJuego("Aurora", "Espíritus"),
    CartaJuego("Azir", "Soldados"),
    CartaJuego("Bard", "Campanas"),
    CartaJuego("Bel'Veth", "Mantarraya"),
    CartaJuego("Blitzcrank", "Gancho"),
    CartaJuego("Brand", "Quemar"),
    CartaJuego("Braum", "Bigote"),
    CartaJuego("Briar", "Hambre"),
    CartaJuego("Caitlyn", "Francotiradora"),
    CartaJuego("Camille", "Tijeras"),
    CartaJuego("Cassiopeia", "Piedra"),
    CartaJuego("Cho'Gath", "Crecer"),
    CartaJuego("Corki", "Paquete"),
    CartaJuego("Darius", "Guillotina"),
    CartaJuego("Diana", "Luna"),
    CartaJuego("Dr. Mundo", "Donde quiere"),
    CartaJuego("Draven", "Hachas"),
    CartaJuego("Ekko", "Rebobinar"),
    CartaJuego("Elise", "Araña"),
    CartaJuego("Evelynn", "Invisible"),
    CartaJuego("Ezreal", "Museo"),
    CartaJuego("Fiddlesticks", "Espantapájaros"),
    CartaJuego("Fiora", "Duelo"),
    CartaJuego("Fizz", "Saltarín"),
    CartaJuego("Galio", "Estatua"),
    CartaJuego("Gangplank", "Naranjas"),
    CartaJuego("Garen", "Arbusto"),
    CartaJuego("Gnar", "Enojo"),
    CartaJuego("Gragas", "Barril"),
    CartaJuego("Graves", "Cigarro"),
    CartaJuego("Gwen", "Costura"),
    CartaJuego("Hecarim", "Caballo"),
    CartaJuego("Heimerdinger", "Torretas"),
    CartaJuego("Hwei", "Pintor"),
    CartaJuego("Illaoi", "Tentáculos"),
    CartaJuego("Irelia", "Danza"),
    CartaJuego("Ivern", "Margarita"),
    CartaJuego("Janna", "Tornado"),
    CartaJuego("Jarvan IV", "Cráter"),
    CartaJuego("Jax", "Lámpara"),
    CartaJuego("Jayce", "Martillo"),
    CartaJuego("Jhin", "Cuatro"),
    CartaJuego("Jinx", "Cohetes"),
    CartaJuego("K'Sante", "Tanque"),
    CartaJuego("Kai'Sa", "Piel"),
    CartaJuego("Kalista", "Venganza"),
    CartaJuego("Karma", "Mantra"),
    CartaJuego("Karthus", "Réquiem"),
    CartaJuego("Kassadin", "Vacío"),
    CartaJuego("Katarina", "Dagas"),
    CartaJuego("Kayle", "Justicia"),
    CartaJuego("Kayn", "Guadaña"),
    CartaJuego("Kennen", "Electricidad"),
    CartaJuego("Kha'Zix", "Evolución"),
    CartaJuego("Kindred", "Lobo"),
    CartaJuego("Kled", "Lagartija"),
    CartaJuego("Kog'Maw", "Saliva"),
    CartaJuego("LeBlanc", "Engaño"),
    CartaJuego("Lee Sin", "Ciego"),
    CartaJuego("Leona", "Sol"),
    CartaJuego("Lillia", "Dormir"),
    CartaJuego("Lissandra", "Hielo"),
    CartaJuego("Lucian", "Pistolas"),
    CartaJuego("Lulu", "Hada"),
    CartaJuego("Lux", "Arcoíris"),
    CartaJuego("Malphite", "Roca"),
    CartaJuego("Malzahar", "Supresión"),
    CartaJuego("Maokai", "Árbol"),
    CartaJuego("Master Yi", "Alpha"),
    CartaJuego("Milio", "Fuego"),
    CartaJuego("Miss Fortune", "Pirata"),
    CartaJuego("Mordekaiser", "Reino"),
    CartaJuego("Morgana", "Cárcel"),
    CartaJuego("Naafiri", "Manada"),
    CartaJuego("Nami", "Ola"),
    CartaJuego("Nasus", "Farmear"),
    CartaJuego("Nautilus", "Ancla"),
    CartaJuego("Neeko", "Camuflaje"),
    CartaJuego("Nidalee", "Lanza"),
    CartaJuego("Nilah", "Alegría"),
    CartaJuego("Nocturne", "Oscuridad"),
    CartaJuego("Nunu & Willump", "Bola"),
    CartaJuego("Olaf", "Vikingo"),
    CartaJuego("Orianna", "Bola"),
    CartaJuego("Ornn", "Forja"),
    CartaJuego("Pantheon", "Espartano"),
    CartaJuego("Poppy", "Héroe"),
    CartaJuego("Pyke", "Lista"),
    CartaJuego("Qiyana", "Elementos"),
    CartaJuego("Quinn", "Valor"),
    CartaJuego("Rakan", "Encanto"),
    CartaJuego("Rammus", "Ok"),
    CartaJuego("Rek'Sai", "Túneles"),
    CartaJuego("Rell", "Metal"),
    CartaJuego("Renata Glasc", "Química"),
    CartaJuego("Renekton", "Cocodrilo"),
    CartaJuego("Rengar", "Trofeos"),
    CartaJuego("Riven", "Rota"),
    CartaJuego("Rumble", "Calor"),
    CartaJuego("Ryze", "Pergamino"),
    CartaJuego("Samira", "Estilo"),
    CartaJuego("Sejuani", "Jabalí"),
    CartaJuego("Senna", "Niebla"),
    CartaJuego("Seraphine", "Cantante"),
    CartaJuego("Sett", "Abdominales"),
    CartaJuego("Shaco", "Clon"),
    CartaJuego("Shen", "Equilibrio"),
    CartaJuego("Shyvana", "Dragón"),
    CartaJuego("Singed", "Veneno"),
    CartaJuego("Sion", "Tren"),
    CartaJuego("Sivir", "Boomerang"),
    CartaJuego("Skarner", "Escorpión"),
    CartaJuego("Smolder", "Mamá"),
    CartaJuego("Sona", "Muda"),
    CartaJuego("Soraka", "Banana"),
    CartaJuego("Swain", "Cuervos"),
    CartaJuego("Sylas", "Robar"),
    CartaJuego("Syndra", "Poder"),
    CartaJuego("Tahm Kench", "Rana"),
    CartaJuego("Taliyah", "Muro"),
    CartaJuego("Talon", "Parkour"),
    CartaJuego("Taric", "Gemas"),
    CartaJuego("Teemo", "Setas"),
    CartaJuego("Thresh", "Linterna"),
    CartaJuego("Tristana", "Cañón"),
    CartaJuego("Trundle", "Troll"),
    CartaJuego("Tryndamere", "Inmortal"),
    CartaJuego("Twisted Fate", "Cartas"),
    CartaJuego("Twitch", "Rata"),
    CartaJuego("Udyr", "Posiciones"),
    CartaJuego("Urgot", "Piernas"),
    CartaJuego("Varus", "Flecha"),
    CartaJuego("Vayne", "Gafas"),
    CartaJuego("Veigar", "Pequeño"),
    CartaJuego("Vel'Koz", "Geometría"),
    CartaJuego("Vex", "Sombra"),
    CartaJuego("Vi", "Guanteletes"),
    CartaJuego("Viego", "Rey"),
    CartaJuego("Viktor", "Láser"),
    CartaJuego("Vladimir", "Sangre"),
    CartaJuego("Volibear", "Oso"),
    CartaJuego("Warwick", "Olfato"),
    CartaJuego("Wukong", "Mono"),
    CartaJuego("Xayah", "Plumas"),
    CartaJuego("Xerath", "Arcano"),
    CartaJuego("Xin Zhao", "Lanza"),
    CartaJuego("Yasuo", "Viento"),
    CartaJuego("Yone", "Espíritu"),
    CartaJuego("Yorick", "Pala"),
    CartaJuego("Yuumi", "Gato"),
    CartaJuego("Zac", "Gelatina"),
    CartaJuego("Zed", "Sombras"),
    CartaJuego("Zeri", "Chispa"),
    CartaJuego("Ziggs", "Bombas"),
    CartaJuego("Zilean", "Reloj"),
    CartaJuego("Zoe", "Dormir"),
    CartaJuego("Zyra", "Plantas"),
  ],

  // ======================================================
  // 2. ANIMALES
  // ======================================================
  "🐾 Animales": [
    CartaJuego("León", "Rey"),
    CartaJuego("Tiburón", "Aleta"),
    CartaJuego("Águila", "Visión"),
    CartaJuego("Perro", "Lealtad"),
    CartaJuego("Gato", "Independiente"),
    CartaJuego("Elefante", "Memoria"),
    CartaJuego("Jirafa", "Altura"),
    CartaJuego("Pingüino", "Esmoquin"),
    CartaJuego("Canguro", "Bolsa"),
    CartaJuego("Panda", "Bambú"),
    CartaJuego("Lobo", "Luna"),
    CartaJuego("Murciélago", "Eco"),
    CartaJuego("Serpiente", "Veneno"),
    CartaJuego("Cocodrilo", "Lágrimas"),
    CartaJuego("Camaleón", "Color"),
    CartaJuego("Caballo", "Galope"),
    CartaJuego("Vaca", "Leche"),
    CartaJuego("Cerdo", "Lodo"),
    CartaJuego("Oveja", "Lana"),
    CartaJuego("Gallina", "Huevo"),
    CartaJuego("Abeja", "Colmena"),
    CartaJuego("Hormiga", "Fuerza"),
    CartaJuego("Mariposa", "Transformación"),
    CartaJuego("Pulpo", "Tinta"),
    CartaJuego("Delfín", "Inteligente"),
    CartaJuego("Ballena", "Plancton"),
    CartaJuego("Oso Polar", "Hielo"),
    CartaJuego("Zorro", "Astucia"),
    CartaJuego("Búho", "Sabiduría"),
    CartaJuego("Ratón", "Queso"),
    CartaJuego("Conejo", "Zanahoria"),
    CartaJuego("Tortuga", "Lenta"),
    CartaJuego("Caracol", "Casa"),
    CartaJuego("Araña", "Red"),
    CartaJuego("Escorpión", "Aguijón"),
    CartaJuego("Cebra", "Rayas"),
    CartaJuego("Hipopótamo", "Río"),
    CartaJuego("Rinoceronte", "Cuerno"),
    CartaJuego("Gorila", "Selva"),
    CartaJuego("Koala", "Eucalipto"),
    CartaJuego("Perezoso", "Lento"),
    CartaJuego("Flamenco", "Rosa"),
    CartaJuego("Pavo Real", "Abanico"),
    CartaJuego("Loro", "Hablar"),
    CartaJuego("Cisne", "Feo"),
    CartaJuego("Castor", "Presa"),
    CartaJuego("Topo", "Tierra"),
    CartaJuego("Erizo", "Púas"),
  ],

  // ======================================================
  // 3. COMIDA
  // ======================================================
  "🍕 Comida": [
    CartaJuego("Pizza", "Triángulo"),
    CartaJuego("Sushi", "Crudo"),
    CartaJuego("Hamburguesa", "Estadounidense"),
    CartaJuego("Tacos", "Tortilla"),
    CartaJuego("Pasta", "Italia"),
    CartaJuego("Helado", "Derretido"),
    CartaJuego("Chocolate", "Cacao"),
    CartaJuego("Café", "Despertar"),
    CartaJuego("Té", "Inglés"),
    CartaJuego("Pan", "Harina"),
    CartaJuego("Queso", "Ratón"),
    CartaJuego("Huevo", "Gallina"),
    CartaJuego("Leche", "Calcio"),
    CartaJuego("Manzana", "Doctor"),
    CartaJuego("Banana", "Potasio"),
    CartaJuego("Naranja", "Vitamina C"),
    CartaJuego("Uva", "Vino"),
    CartaJuego("Fresa", "Crema"),
    CartaJuego("Sandía", "Semillas"),
    CartaJuego("Limón", "Ácido"),
    CartaJuego("Cebolla", "Llorar"),
    CartaJuego("Ajo", "Vampiro"),
    CartaJuego("Papa", "Frita"),
    CartaJuego("Tomate", "Salsa"),
    CartaJuego("Zanahoria", "Vista"),
    CartaJuego("Lechuga", "Dieta"),
    CartaJuego("Arroz", "Blanco"),
    CartaJuego("Frijoles", "Gas"),
    CartaJuego("Maíz", "Palomitas"),
    CartaJuego("Pescado", "Mar"),
    CartaJuego("Pollo", "Frito"),
    CartaJuego("Carne", "Asado"),
    CartaJuego("Tocino", "Desayuno"),
    CartaJuego("Salchicha", "Hot Dog"),
    CartaJuego("Jamón", "Sándwich"),
    CartaJuego("Miel", "Oso"),
    CartaJuego("Azúcar", "Dulce"),
    CartaJuego("Sal", "Mar"),
    CartaJuego("Pimienta", "Estornudo"),
    CartaJuego("Aceite", "Freír"),
    CartaJuego("Vinagre", "Ensalada"),
    CartaJuego("Ketchup", "Rojo"),
    CartaJuego("Mayonesa", "Blanco"),
    CartaJuego("Mostaza", "Amarillo"),
    CartaJuego("Sopa", "Cuchara"),
    CartaJuego("Cereal", "Leche"),
    CartaJuego("Galleta", "Horno"),
    CartaJuego("Pastel", "Cumpleaños"),
  ],

  // ======================================================
  // 4. PAÍSES
  // ======================================================
  "🌍 Países": [
    CartaJuego("Argentina", "Mate"),
    CartaJuego("Brasil", "Carnaval"),
    CartaJuego("Chile", "Largo"),
    CartaJuego("México", "Picante"),
    CartaJuego("Estados Unidos", "Águila"),
    CartaJuego("Canadá", "Hoja"),
    CartaJuego("España", "Toro"),
    CartaJuego("Francia", "Torre"),
    CartaJuego("Italia", "Bota"),
    CartaJuego("Alemania", "Muro"),
    CartaJuego("Reino Unido", "Reina"),
    CartaJuego("Rusia", "Frío"),
    CartaJuego("China", "Muralla"),
    CartaJuego("Japón", "Sol Naciente"),
    CartaJuego("India", "Especias"),
    CartaJuego("Egipto", "Pirámide"),
    CartaJuego("Australia", "Canguro"),
    CartaJuego("Sudáfrica", "Safari"),
    CartaJuego("Perú", "Inca"),
    CartaJuego("Colombia", "Café"),
    CartaJuego("Venezuela", "Petróleo"),
    CartaJuego("Uruguay", "Celeste"),
    CartaJuego("Cuba", "Tabaco"),
    CartaJuego("Jamaica", "Rápido"),
    CartaJuego("Grecia", "Dioses"),
    CartaJuego("Turquía", "Puente"),
    CartaJuego("Suiza", "Reloj"),
    CartaJuego("Suecia", "Muebles"),
    CartaJuego("Noruega", "Vikingos"),
    CartaJuego("Holanda", "Tulipanes"),
    CartaJuego("Bélgica", "Chocolate"),
    CartaJuego("Portugal", "Navegantes"),
    CartaJuego("Irlanda", "Trébol"),
    CartaJuego("Escocia", "Falda"),
    CartaJuego("Corea del Sur", "K-Pop"),
    CartaJuego("Vietnam", "Guerra"),
    CartaJuego("Tailandia", "Elefantes"),
    CartaJuego("Israel", "Santo"),
    CartaJuego("Arabia Saudita", "Desierto"),
    CartaJuego("Marruecos", "Zoco"),
    CartaJuego("Kenia", "Corredores"),
    CartaJuego("Madagascar", "Película"),
    CartaJuego("Nueva Zelanda", "Anillo"),
    CartaJuego("Antártida", "Hielo"),
  ],

  // ======================================================
  // 5. OBJETOS DE LA CASA
  // ======================================================
  "🏠 Casa": [
    CartaJuego("Cama", "Dormir"),
    CartaJuego("Sofá", "Televisión"),
    CartaJuego("Mesa", "Comer"),
    CartaJuego("Silla", "Sentarse"),
    CartaJuego("Lámpara", "Luz"),
    CartaJuego("Espejo", "Reflejo"),
    CartaJuego("Alfombra", "Piso"),
    CartaJuego("Cortina", "Ventana"),
    CartaJuego("Puerta", "Entrada"),
    CartaJuego("Ventana", "Vista"),
    CartaJuego("Llave", "Abrir"),
    CartaJuego("Reloj", "Hora"),
    CartaJuego("Televisión", "Canales"),
    CartaJuego("Control Remoto", "Pilas"),
    CartaJuego("Teléfono", "Llamada"),
    CartaJuego("Computadora", "Internet"),
    CartaJuego("Cargador", "Batería"),
    CartaJuego("Refrigerador", "Frío"),
    CartaJuego("Estufa", "Calor"),
    CartaJuego("Microondas", "Rápido"),
    CartaJuego("Licuadora", "Batido"),
    CartaJuego("Tostadora", "Pan"),
    CartaJuego("Lavadora", "Ropa"),
    CartaJuego("Secadora", "Caliente"),
    CartaJuego("Plancha", "Arrugas"),
    CartaJuego("Aspiradora", "Polvo"),
    CartaJuego("Escoba", "Barrer"),
    CartaJuego("Trapeador", "Agua"),
    CartaJuego("Basura", "Olor"),
    CartaJuego("Inodoro", "Baño"),
    CartaJuego("Ducha", "Agua"),
    CartaJuego("Toalla", "Secar"),
    CartaJuego("Jabón", "Espuma"),
    CartaJuego("Cepillo de Dientes", "Pasta"),
    CartaJuego("Papel Higiénico", "Rollo"),
    CartaJuego("Almohada", "Cabeza"),
    CartaJuego("Sábana", "Cubrir"),
    CartaJuego("Cobija", "Invierno"),
    CartaJuego("Vaso", "Beber"),
    CartaJuego("Plato", "Servir"),
    CartaJuego("Cuchara", "Sopa"),
    CartaJuego("Tenedor", "Pinchar"),
    CartaJuego("Cuchillo", "Cortar"),
    CartaJuego("Sartén", "Freír"),
    CartaJuego("Olla", "Hervir"),
  ],

  // ======================================================
  // 6. PROFESIONES
  // ======================================================
  "💼 Profesiones": [
    CartaJuego("Médico", "Estetoscopio"),
    CartaJuego("Enfermera", "Cuidado"),
    CartaJuego("Dentista", "Dientes"),
    CartaJuego("Veterinario", "Animales"),
    CartaJuego("Profesor", "Pizarra"),
    CartaJuego("Estudiante", "Libros"),
    CartaJuego("Policía", "Placa"),
    CartaJuego("Bombero", "Manguera"),
    CartaJuego("Juez", "Mazo"),
    CartaJuego("Abogado", "Leyes"),
    CartaJuego("Ingeniero", "Casco"),
    CartaJuego("Arquitecto", "Planos"),
    CartaJuego("Albañil", "Ladrillos"),
    CartaJuego("Carpintero", "Madera"),
    CartaJuego("Plomero", "Tuberías"),
    CartaJuego("Electricista", "Cables"),
    CartaJuego("Mecánico", "Coche"),
    CartaJuego("Cocinero", "Gorro"),
    CartaJuego("Mesero", "Propina"),
    CartaJuego("Panadero", "Harina"),
    CartaJuego("Carnicero", "Cuchillo"),
    CartaJuego("Peluquero", "Tijeras"),
    CartaJuego("Maquillador", "Brocha"),
    CartaJuego("Actor", "Cine"),
    CartaJuego("Cantante", "Micrófono"),
    CartaJuego("Músico", "Instrumento"),
    CartaJuego("Pintor", "Lienzo"),
    CartaJuego("Escritor", "Libro"),
    CartaJuego("Periodista", "Noticia"),
    CartaJuego("Fotógrafo", "Cámara"),
    CartaJuego("Piloto", "Avión"),
    CartaJuego("Azafata", "Vuelo"),
    CartaJuego("Taxista", "Pasajero"),
    CartaJuego("Conductor de Autobús", "Parada"),
    CartaJuego("Granjero", "Campo"),
    CartaJuego("Pescador", "Red"),
    CartaJuego("Jardinero", "Plantas"),
    CartaJuego("Científico", "Laboratorio"),
    CartaJuego("Astronauta", "Espacio"),
    CartaJuego("Soldado", "Uniforme"),
    CartaJuego("Sacerdote", "Iglesia"),
    CartaJuego("Político", "Votos"),
    CartaJuego("Deportista", "Entrenamiento"),
    CartaJuego("Entrenador", "Silbato"),
    CartaJuego("Árbitro", "Tarjeta"),
    CartaJuego("Detective", "Lupa"),
    CartaJuego("Espía", "Secreto"),
  ],

  // ======================================================
  // 7. DEPORTES
  // ======================================================
  "⚽ Deportes": [
    CartaJuego("Fútbol", "Gol"),
    CartaJuego("Baloncesto", "Canasta"),
    CartaJuego("Tenis", "Raqueta"),
    CartaJuego("Béisbol", "Bate"),
    CartaJuego("Fútbol Americano", "Casco"),
    CartaJuego("Rugby", "Ovalo"),
    CartaJuego("Voleibol", "Red"),
    CartaJuego("Golf", "Hoyo"),
    CartaJuego("Boxeo", "Guantes"),
    CartaJuego("Natación", "Agua"),
    CartaJuego("Atletismo", "Correr"),
    CartaJuego("Ciclismo", "Rueda"),
    CartaJuego("Automovilismo", "Motor"),
    CartaJuego("Motociclismo", "Casco"),
    CartaJuego("Gimnasia", "Flexible"),
    CartaJuego("Patinaje", "Hielo"),
    CartaJuego("Esquí", "Nieve"),
    CartaJuego("Surf", "Ola"),
    CartaJuego("Skate", "Tabla"),
    CartaJuego("Karate", "Cinturón"),
    CartaJuego("Judo", "Agarre"),
    CartaJuego("Taekwondo", "Patada"),
    CartaJuego("Lucha Libre", "Máscara"),
    CartaJuego("Esgrima", "Espada"),
    CartaJuego("Tiro con Arco", "Flecha"),
    CartaJuego("Tenis de Mesa", "Ping Pong"),
    CartaJuego("Bádminton", "Pluma"),
    CartaJuego("Hockey", "Disco"),
    CartaJuego("Críquet", "Bate"),
    CartaJuego("Balonmano", "Mano"),
    CartaJuego("Waterpolo", "Piscina"),
    CartaJuego("Remo", "Bote"),
    CartaJuego("Halterofilia", "Pesas"),
    CartaJuego("Escalada", "Montaña"),
    CartaJuego("Paracaidismo", "Caída"),
    CartaJuego("Buceo", "Profundidad"),
    CartaJuego("Pesca", "Caña"),
    CartaJuego("Caza", "Escopeta"),
    CartaJuego("Bolos", "Chuza"),
    CartaJuego("Billar", "Taco"),
    CartaJuego("Ajedrez", "Jaque"),
    CartaJuego("Dardos", "Diana"),
    CartaJuego("Yoga", "Postura"),
    CartaJuego("Crossfit", "Intenso"),
  ],

  // ======================================================
  // 8. CINE
  // ======================================================
  "🎬 Cine": [
    CartaJuego("Star Wars", "Fuerza"),
    CartaJuego("Harry Potter", "Varita"),
    CartaJuego("El Señor de los Anillos", "Anillo"),
    CartaJuego("Avengers", "Chasquido"),
    CartaJuego("Batman", "Noche"),
    CartaJuego("Superman", "Criptonita"),
    CartaJuego("Spiderman", "Red"),
    CartaJuego("Titanic", "Iceberg"),
    CartaJuego("Avatar", "Azul"),
    CartaJuego("Jurassic Park", "Dinosaurio"),
    CartaJuego("El Rey León", "Ciclo"),
    CartaJuego("Toy Story", "Juguetes"),
    CartaJuego("Shrek", "Ogro"),
    CartaJuego("Frozen", "Hielo"),
    CartaJuego("Buscando a Nemo", "Pez"),
    CartaJuego("Piratas del Caribe", "Barco"),
    CartaJuego("Rápidos y Furiosos", "Familia"),
    CartaJuego("Misión Imposible", "Espía"),
    CartaJuego("James Bond", "007"),
    CartaJuego("Indiana Jones", "Látigo"),
    CartaJuego("Volver al Futuro", "Auto"),
    CartaJuego("Terminator", "Robot"),
    CartaJuego("Matrix", "Pastilla"),
    CartaJuego("El Padrino", "Oferta"),
    CartaJuego("Rocky", "Boxeo"),
    CartaJuego("Forrest Gump", "Correr"),
    CartaJuego("Gladiador", "Arena"),
    CartaJuego("Coco", "Recuerdo"),
    CartaJuego("Intensamente", "Emociones"),
    CartaJuego("Up", "Globos"),
    CartaJuego("Los Increíbles", "Traje"),
    CartaJuego("Kung Fu Panda", "Guerrero"),
    CartaJuego("Madagascar", "Mover"),
    CartaJuego("La Era de Hielo", "Bellota"),
    CartaJuego("Minions", "Banana"),
    CartaJuego("Mi Villano Favorito", "Luna"),
    CartaJuego("Hotel Transylvania", "Drácula"),
    CartaJuego("Crepúsculo", "Vampiro"),
    CartaJuego("Los Juegos del Hambre", "Arco"),
    CartaJuego("Divergente", "Facciones"),
    CartaJuego("Maze Runner", "Laberinto"),
    CartaJuego("IT", "Globo"),
    CartaJuego("El Exorcista", "Cama"),
    CartaJuego("El Resplandor", "Hacha"),
    CartaJuego("Saw", "Juego"),
  ],

  // ======================================================
  // 9. VIDEOJUEGOS
  // ======================================================
  "🎮 Videojuegos": [
    CartaJuego("Mario Bros", "Fontanero"),
    CartaJuego("Zelda", "Princesa"),
    CartaJuego("Pokémon", "Captura"),
    CartaJuego("Minecraft", "Bloques"),
    CartaJuego("Fortnite", "Construcción"),
    CartaJuego("League of Legends", "Grieta"),
    CartaJuego("Dota 2", "Ancestro"),
    CartaJuego("Overwatch", "Héroes"),
    CartaJuego("Valorant", "Spike"),
    CartaJuego("CS:GO", "Bomba"),
    CartaJuego("Call of Duty", "Guerra"),
    CartaJuego("GTA", "Robo"),
    CartaJuego("FIFA", "Balón"),
    CartaJuego("Among Us", "Impostor"),
    CartaJuego("Roblox", "Cuadrado"),
    CartaJuego("Clash Royale", "Torres"),
    CartaJuego("Clash of Clans", "Aldea"),
    CartaJuego("Candy Crush", "Dulces"),
    CartaJuego("Angry Birds", "Cerdos"),
    CartaJuego("Plantas vs Zombies", "Jardín"),
    CartaJuego("Tetris", "Líneas"),
    CartaJuego("Pac-Man", "Fantasmas"),
    CartaJuego("Sonic", "Anillos"),
    CartaJuego("Donkey Kong", "Barril"),
    CartaJuego("Street Fighter", "Pelea"),
    CartaJuego("Mortal Kombat", "Fatality"),
    CartaJuego("Tekken", "Torneo"),
    CartaJuego("Super Smash Bros", "Plataforma"),
    CartaJuego("God of War", "Dioses"),
    CartaJuego("Halo", "Jefe Maestro"),
    CartaJuego("Gears of War", "Lancer"),
    CartaJuego("The Last of Us", "Hongo"),
    CartaJuego("Uncharted", "Tesoro"),
    CartaJuego("Tomb Raider", "Arqueóloga"),
    CartaJuego("Resident Evil", "Zombies"),
    CartaJuego("Silent Hill", "Niebla"),
    CartaJuego("Final Fantasy", "Cristales"),
    CartaJuego("World of Warcraft", "Horda"),
    CartaJuego("Diablo", "Infierno"),
    CartaJuego("Starcraft", "Espacio"),
    CartaJuego("Portal", "Pastel"),
    CartaJuego("Half-Life", "Palanca"),
    CartaJuego("Cyberpunk", "Futuro"),
    CartaJuego("Elden Ring", "Anillo"),
    CartaJuego("Dark Souls", "Hoguera"),
  ],

  // ======================================================
  // 10. LUGARES
  // ======================================================
  "📍 Lugares": [
    CartaJuego("Aeropuerto", "Maletas"),
    CartaJuego("Estación de Tren", "Vías"),
    CartaJuego("Puerto", "Barcos"),
    CartaJuego("Parada de Autobús", "Espera"),
    CartaJuego("Metro", "Subterráneo"),
    CartaJuego("Hospital", "Emergencia"),
    CartaJuego("Escuela", "Aprender"),
    CartaJuego("Universidad", "Grado"),
    CartaJuego("Biblioteca", "Silencio"),
    CartaJuego("Museo", "Antiguo"),
    CartaJuego("Cine", "Palomitas"),
    CartaJuego("Teatro", "Telón"),
    CartaJuego("Estadio", "Gradas"),
    CartaJuego("Parque", "Juegos"),
    CartaJuego("Zoológico", "Jaulas"),
    CartaJuego("Circo", "Carpa"),
    CartaJuego("Playa", "Arena"),
    CartaJuego("Montaña", "Cima"),
    CartaJuego("Bosque", "Árboles"),
    CartaJuego("Selva", "Humedad"),
    CartaJuego("Desierto", "Sed"),
    CartaJuego("Isla", "Aislado"),
    CartaJuego("Ciudad", "Edificios"),
    CartaJuego("Pueblo", "Tranquilo"),
    CartaJuego("Granja", "Animales"),
    CartaJuego("Fábrica", "Humo"),
    CartaJuego("Oficina", "Escritorio"),
    CartaJuego("Tienda", "Comprar"),
    CartaJuego("Supermercado", "Carrito"),
    CartaJuego("Restaurante", "Menú"),
    CartaJuego("Hotel", "Recepción"),
    CartaJuego("Banco", "Dinero"),
    CartaJuego("Comisaría", "Celdas"),
    CartaJuego("Estación de Bomberos", "Sirena"),
    CartaJuego("Iglesia", "Rezar"),
    CartaJuego("Cementerio", "Tumbas"),
    CartaJuego("Gimnasio", "Sudar"),
    CartaJuego("Piscina", "Cloro"),
    CartaJuego("Spa", "Masaje"),
    CartaJuego("Peluquería", "Corte"),
    CartaJuego("Taller", "Grasa"),
    CartaJuego("Gasolinera", "Combustible"),
    CartaJuego("Estacionamiento", "Coche"),
    CartaJuego("Puente", "Cruzar"),
    CartaJuego("Túnel", "Oscuro"),
  ],

  // ======================================================
  // 11. MÚSICA
  // ======================================================
  "🎵 Música": [
    CartaJuego("Guitarra", "Cuerdas"),
    CartaJuego("Piano", "Teclas"),
    CartaJuego("Batería", "Ritmo"),
    CartaJuego("Violín", "Arco"),
    CartaJuego("Flauta", "Viento"),
    CartaJuego("Trompeta", "Metal"),
    CartaJuego("Saxofón", "Jazz"),
    CartaJuego("Clarinete", "Madera"),
    CartaJuego("Arpa", "Ángel"),
    CartaJuego("Acordeón", "Fuelle"),
    CartaJuego("Bajo", "Grave"),
    CartaJuego("Ukelele", "Hawai"),
    CartaJuego("Banjo", "Country"),
    CartaJuego("Mandolina", "Italia"),
    CartaJuego("Violonchelo", "Sentado"),
    CartaJuego("Contrabajo", "Grande"),
    CartaJuego("Tuba", "Grave"),
    CartaJuego("Trombón", "Vara"),
    CartaJuego("Oboe", "Orquesta"),
    CartaJuego("Fagot", "Doble"),
    CartaJuego("Xilófono", "Golpear"),
    CartaJuego("Marimba", "Madera"),
    CartaJuego("Tambor", "Marcha"),
    CartaJuego("Platillos", "Choque"),
    CartaJuego("Triángulo", "Tintineo"),
    CartaJuego("Pandereta", "Gospel"),
    CartaJuego("Maracas", "Salsa"),
    CartaJuego("Bongo", "Manos"),
    CartaJuego("Conga", "Cuba"),
    CartaJuego("Timbales", "Orquesta"),
    CartaJuego("Gaita", "Escocia"),
    CartaJuego("Armónica", "Bolsillo"),
    CartaJuego("Órgano", "Iglesia"),
    CartaJuego("Sintetizador", "Electrónica"),
    CartaJuego("Teclado", "Eléctrico"),
    CartaJuego("Guitarra Eléctrica", "Amplificador"),
    CartaJuego("Micrófono", "Voz"),
    CartaJuego("Altavoz", "Sonido"),
    CartaJuego("Auriculares", "Privado"),
    CartaJuego("Dj", "Mezcla"),
    CartaJuego("Director", "Batuta"),
    CartaJuego("Cantante", "Letra"),
    CartaJuego("Coro", "Voces"),
    CartaJuego("Banda", "Grupo"),
    CartaJuego("Orquesta", "Sinfonía"),
  ],

  // ======================================================
  // 12. ROPA
  // ======================================================
  "👗 Ropa": [
    CartaJuego("Camisa", "Botones"),
    CartaJuego("Camiseta", "Casual"),
    CartaJuego("Pantalón", "Piernas"),
    CartaJuego("Jeans", "Azul"),
    CartaJuego("Falda", "Viento"),
    CartaJuego("Vestido", "Fiesta"),
    CartaJuego("Traje", "Formal"),
    CartaJuego("Corbata", "Cuello"),
    CartaJuego("Moño", "Elegante"),
    CartaJuego("Abrigo", "Invierno"),
    CartaJuego("Chaqueta", "Cierre"),
    CartaJuego("Suéter", "Lana"),
    CartaJuego("Sudadera", "Capucha"),
    CartaJuego("Chaleco", "Sin mangas"),
    CartaJuego("Shorts", "Verano"),
    CartaJuego("Traje de Baño", "Playa"),
    CartaJuego("Bikini", "Dos piezas"),
    CartaJuego("Ropa Interior", "Debajo"),
    CartaJuego("Calcetines", "Pies"),
    CartaJuego("Zapatos", "Suela"),
    CartaJuego("Zapatillas", "Deporte"),
    CartaJuego("Botas", "Lluvia"),
    CartaJuego("Sandalias", "Dedos"),
    CartaJuego("Tacones", "Altura"),
    CartaJuego("Pantuflas", "Casa"),
    CartaJuego("Gorro", "Cabeza"),
    CartaJuego("Sombrero", "Sol"),
    CartaJuego("Gorra", "Visera"),
    CartaJuego("Bufanda", "Garganta"),
    CartaJuego("Guantes", "Manos"),
    CartaJuego("Cinturón", "Ajuste"),
    CartaJuego("Reloj", "Muñeca"),
    CartaJuego("Collar", "Perlas"),
    CartaJuego("Pulsera", "Mano"),
    CartaJuego("Anillo", "Dedo"),
    CartaJuego("Pendientes", "Orejas"),
    CartaJuego("Gafas", "Vista"),
    CartaJuego("Gafas de Sol", "Oscuro"),
    CartaJuego("Bolso", "Mujer"),
    CartaJuego("Mochila", "Espalda"),
    CartaJuego("Cartera", "Dinero"),
    CartaJuego("Maleta", "Viaje"),
    CartaJuego("Paraguas", "Lluvia"),
    CartaJuego("Impermeable", "Agua"),
    CartaJuego("Pijama", "Dormir"),
  ],

  // ======================================================
  // 13. CUERPO
  // ======================================================
  "💪 Cuerpo": [
    CartaJuego("Cabeza", "Pensar"),
    CartaJuego("Pelo", "Peinar"),
    CartaJuego("Ojos", "Ver"),
    CartaJuego("Nariz", "Oler"),
    CartaJuego("Boca", "Comer"),
    CartaJuego("Dientes", "Morder"),
    CartaJuego("Lengua", "Sabor"),
    CartaJuego("Orejas", "Oír"),
    CartaJuego("Cuello", "Girar"),
    CartaJuego("Hombros", "Carga"),
    CartaJuego("Brazos", "Abrazo"),
    CartaJuego("Codos", "Doblar"),
    CartaJuego("Manos", "Tocar"),
    CartaJuego("Dedos", "Huella"),
    CartaJuego("Uñas", "Rascar"),
    CartaJuego("Pecho", "Respirar"),
    CartaJuego("Corazón", "Latido"),
    CartaJuego("Estómago", "Hambre"),
    CartaJuego("Espalda", "Columna"),
    CartaJuego("Cintura", "Cinturón"),
    CartaJuego("Caderas", "Baile"),
    CartaJuego("Piernas", "Caminar"),
    CartaJuego("Rodillas", "Rezar"),
    CartaJuego("Tobillos", "Torcedura"),
    CartaJuego("Pies", "Pasos"),
    CartaJuego("Piel", "Tacto"),
    CartaJuego("Huesos", "Esqueleto"),
    CartaJuego("Músculos", "Fuerza"),
    CartaJuego("Sangre", "Rojo"),
    CartaJuego("Cerebro", "Mente"),
    CartaJuego("Pulmones", "Aire"),
    CartaJuego("Hígado", "Filtro"),
    CartaJuego("Riñones", "Agua"),
    CartaJuego("Intestinos", "Tubo"),
    CartaJuego("Garganta", "Tragar"),
    CartaJuego("Voz", "Sonido"),
    CartaJuego("Lágrimas", "Tristeza"),
    CartaJuego("Sudor", "Calor"),
    CartaJuego("Saliva", "Boca"),
    CartaJuego("Ombligo", "Centro"),
    CartaJuego("Barbilla", "Golpe"),
    CartaJuego("Mejillas", "Rubor"),
    CartaJuego("Frente", "Fiebre"),
    CartaJuego("Cejas", "Expresión"),
    CartaJuego("Pestañas", "Deseo"),
  ],

  // ======================================================
  // 14. HÉROES
  // ======================================================
  "🦸 Héroes": [
    CartaJuego("Superman", "Krypton"),
    CartaJuego("Batman", "Murciélago"),
    CartaJuego("Wonder Woman", "Lazo"),
    CartaJuego("Flash", "Rápido"),
    CartaJuego("Aquaman", "Tridente"),
    CartaJuego("Cyborg", "Máquina"),
    CartaJuego("Linterna Verde", "Anillo"),
    CartaJuego("Joker", "Risa"),
    CartaJuego("Harley Quinn", "Bate"),
    CartaJuego("Lex Luthor", "Calvo"),
    CartaJuego("Spider-Man", "Sentido"),
    CartaJuego("Iron Man", "Armadura"),
    CartaJuego("Capitán América", "Escudo"),
    CartaJuego("Thor", "Martillo"),
    CartaJuego("Hulk", "Enojo"),
    CartaJuego("Black Widow", "Espía"),
    CartaJuego("Hawkeye", "Arco"),
    CartaJuego("Dr. Strange", "Tiempo"),
    CartaJuego("Black Panther", "Wakanda"),
    CartaJuego("Scarlet Witch", "Magia"),
    CartaJuego("Vision", "Gema"),
    CartaJuego("Ant-Man", "Pequeño"),
    CartaJuego("Wolverine", "Garras"),
    CartaJuego("Deadpool", "Romper"),
    CartaJuego("Profesor X", "Mente"),
    CartaJuego("Magneto", "Metal"),
    CartaJuego("Storm", "Clima"),
    CartaJuego("Jean Grey", "Fénix"),
    CartaJuego("Cyclops", "Ojos"),
    CartaJuego("Rogue", "Toque"),
    CartaJuego("Thanos", "Guantelete"),
    CartaJuego("Loki", "Mentira"),
    CartaJuego("Venom", "Simbionte"),
    CartaJuego("Green Goblin", "Deslizador"),
    CartaJuego("Doctor Octopus", "Brazos"),
    CartaJuego("Daredevil", "Ciego"),
    CartaJuego("Punisher", "Calavera"),
    CartaJuego("Ghost Rider", "Moto"),
    CartaJuego("Blade", "Vampiro"),
    CartaJuego("Hellboy", "Mano"),
    CartaJuego("Spawn", "Capa"),
    CartaJuego("Invencible", "Sangre"),
    CartaJuego("Homelander", "Leche"),
    CartaJuego("Groot", "Yo soy"),
    CartaJuego("Rocket", "Mapache"),
  ],

  // ======================================================
  // 15. NATURALEZA
  // ======================================================
  "🌲 Naturaleza": [
    CartaJuego("Sol", "Estrella"),
    CartaJuego("Luna", "Noche"),
    CartaJuego("Estrella", "Deseo"),
    CartaJuego("Nube", "Algodón"),
    CartaJuego("Lluvia", "Mojado"),
    CartaJuego("Nieve", "Frío"),
    CartaJuego("Granizo", "Hielo"),
    CartaJuego("Viento", "Invisible"),
    CartaJuego("Tormenta", "Rayo"),
    CartaJuego("Trueno", "Ruido"),
    CartaJuego("Relámpago", "Luz"),
    CartaJuego("Arcoíris", "Colores"),
    CartaJuego("Niebla", "Ciego"),
    CartaJuego("Huracán", "Giro"),
    CartaJuego("Tornado", "Embudo"),
    CartaJuego("Terremoto", "Temblor"),
    CartaJuego("Tsunami", "Ola"),
    CartaJuego("Volcán", "Lava"),
    CartaJuego("Montaña", "Escalar"),
    CartaJuego("Colina", "Pequeña"),
    CartaJuego("Valle", "Bajo"),
    CartaJuego("Río", "Corriente"),
    CartaJuego("Lago", "Quieto"),
    CartaJuego("Mar", "Salado"),
    CartaJuego("Océano", "Profundo"),
    CartaJuego("Cascada", "Caída"),
    CartaJuego("Playa", "Orilla"),
    CartaJuego("Isla", "Rodeada"),
    CartaJuego("Bosque", "Verde"),
    CartaJuego("Selva", "Densa"),
    CartaJuego("Desierto", "Arena"),
    CartaJuego("Oasis", "Agua"),
    CartaJuego("Cueva", "Murciélagos"),
    CartaJuego("Árbol", "Raíz"),
    CartaJuego("Flor", "Olor"),
    CartaJuego("Hierba", "Césped"),
    CartaJuego("Tierra", "Suelo"),
    CartaJuego("Piedra", "Dura"),
    CartaJuego("Fuego", "Quema"),
    CartaJuego("Agua", "Vida"),
    CartaJuego("Aire", "Respirar"),
    CartaJuego("Hielo", "Resbalar"),
    CartaJuego("Metal", "Duro"),
    CartaJuego("Madera", "Tronco"),
    CartaJuego("Oro", "Brillo"),
  ],
};